EDA-Lab: AnalysisEDA Class Reference
AnalysisEDA Class Reference
#include <AnalysisEDA.h>
Public Member Functions
AnalysisEDA (const GraphHandler *graphHandler, const std::vector< std::vector< Logic >> &inputData)
virtual ~AnalysisEDA ()
void run ()
Detailed Description
Definition at line 17 of file AnalysisEDA.h.
Constructor & Destructor Documentation
AnalysisEDA()
AnalysisEDA::AnalysisEDA (const GraphHandler * graphHandler, const std::vector< std::vector< Logic >> & inputData) inline
Definition at line 19 of file AnalysisEDA.h.
~AnalysisEDA()
virtual AnalysisEDA::~AnalysisEDA () inline virtual
Definition at line 22 of file AnalysisEDA.h.
Member Function Documentation
run()
void AnalysisEDA::run ()
Definition at line 11 of file AnalysisEDA.cpp.
References GraphHandler::getAllElements(), and GraphHandler::getAllNets().
Referenced by main().
The documentation for this class was generated from the following files:
implementation/Analysis-EDA/AnalysisEDA.h
implementation/Analysis-EDA/AnalysisEDA.cpp